version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
     steps:
       - checkout
       - run:
           name: Install Dependencies
           command: sudo pip install -U --pre PyBuilder 
       - run:
           name: Unit Tests
           command: run test:unit
      
          
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - run: 
          name: install pybuilder
          command: sudo pip install -U --pre PyBuilder 
            
      - run:
           name: Build Application
           command: echo building
      - persist_to_workspace: 
           root: venv
           paths: 
             - ./
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
    
      
